name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install clang libwayland-dev libpng-dev
    - name: make
      run: make
      env: 
        CC: clang
    - uses: actions/upload-artifact@v4
      with:
        name: wayland-png-viewer - ${{ matrix.os }}
        path: build_opt/wayland-png-viewer
